name: Build and deploy compiler app

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        description: "Environment to configure"
        type: environment

  push:
    branches: [main, develop, 'feature/*', 'release/*', 'hotfix/*']

env:
  ENVIRONMENT: dev
  AZURE_WEBAPP_NAME: compiler
  SOLUTION_NAME: "BlazorBootstrap"
  DOTNET_CORE_VERSION: 6.0.x

jobs:   
  deploy:
    name: Deploy version  
    runs-on: ['self-hosted', 'Windows', 'X64']
    steps:
      - name: Set environment variable
        run: |
          Write-Host $env:INPUT_ENVIRONMENT
          if ($env:INPUT_ENVIRONMENT -ne '') {
            $env:ENV = $env:INPUT_ENVIRONMENT
          } else {
            $env:ENV = 'dev'
          }
        shell: powershell   
      - name: show
        run:  echo ${{ env.ENV }}

